// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoDemoService2.proto

package com.ominext.grpc.demo;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   */
  int getLongitude();
}
